### ISSUE TITLE
nc-time-axis==1.3.1 impossible to install with scitools-iris==3.0.2

### ISSUE THREAD

**Issue by valeriupredoi** [SciTools/nc-time-axis#71] opened 2021-06-17 13:30 UTC
## 📰 Custom Issue

hey @bjlittle I am trying to install `nc-time-axis` the latest version, 1.3.1, since I found an issue in ESMValTool related to it (and we've not had it before, so I am fairly sure it's due to matplotlib 3.4.2 not liking the older nc-time-axis=1.2.0) but nc-time-axis 1.3.1 requires cftime>=1.5 whereas iris=3.0.2 requires cftime<1.3 so I'm shtuck proper :grin:

**Comment by rcomer** [comment] 2021-06-17 14:04
This was deliberate since `nc-time-axis` 1.3.1 broke the Iris tests (see https://github.com/SciTools/iris/pull/4194).  We need to unpin `cftime` in Iris, but I don't think that will be super soon.  Are you able to revert to `matplotlib` 3.4.1?

**Comment by valeriupredoi** [comment] 2021-06-17 14:20
cheers @rcomer - I am trying to see if 3.3.4 does the trick (3.4+  does not cut it), it's fine for us, not a worry, we'll find a workaround, I thought you guys weren't aware of the dependency tree issue :grin:

**Comment by valeriupredoi** [comment] 2021-06-17 15:55
@rcomer we have found a workaround [this issue](https://github.com/ESMValGroup/ESMValTool/issues/2198#issuecomment-863250763) by using an older `matplotlib` (3.3.4) together with `nc-time-axis=1.3.0` but I reckon it's best you guys look at that error raised from withing `matplotlib=3.4.2`, that newer version clearly doesn't like `nc-time-axis=1.3` or older (no idea what's the hap, but raising it here, maybe you can decipher it :mag: )

**Comment by rcomer** [comment] 2021-06-17 16:12
@valeriupredoi that error looks the same as the [one that broke the Iris tests](https://cirrus-ci.com/task/5668414447419392?logs=tests#L603).  In that case, we had `cftime` 1.2.1, `nc-time-axis` 1.3.0 and `matplotlib` 3.4.2.  We assumed that the error came from an incompatibility between these `cftime` and `nc-time-axis` versions.  Could you confirm which combination of these package versions produced this error for you?

**Comment by rcomer** [comment] 2021-06-17 16:34
Sorry, I should have originally said `nc-time-axis` **1.3.0** broke the Iris tests.  The only difference between 1.3.0 and 1.3.1 is the `cftime` pin.

**Comment by valeriupredoi** [comment] 2021-06-18 08:21
hi @rcomer I am **not** getting the error with this combo:
```
(release230-conda) [valeriu@sci2 ~]$ conda list matplotlib
# packages in environment at /home/users/valeriu/miniconda3-June2021/envs/release230-conda:
#
# Name                    Version                   Build  Channel
matplotlib                3.3.4            py39h06a4308_0  
matplotlib-base           3.3.4            py39h2fa2bec_0    conda-forge
(release230-conda) [valeriu@sci2 ~]$ conda list nc-time-axis
# packages in environment at /home/users/valeriu/miniconda3-June2021/envs/release230-conda:
#
# Name                    Version                   Build  Channel
nc-time-axis              1.3.0                    pypi_0    pypi
```
I would, however, get the error if I bumped `matplotlib` to `3.4.2` - the problem with you guys, I assume, is that the test environment is using matplotlib 3.4+

**Comment by rcomer** [comment] 2021-06-18 09:01
From the traceback, the offending call in `nc-time-axis` is here:

https://github.com/SciTools/nc-time-axis/blob/b45931386ac97e0bfb1357d50542a6310149ca7e/nc_time_axis/__init__.py#L177-L183

As far as I can see, only the calendar can be any sort of string.  We can reproduce the error with `cftime` 1.2.1 by simply

```python
In [1]: import cftime

In [2]: cftime.__version__
Out[2]: '1.2.1'

In [3]: import numpy as np

In [4]: cftime.datetime(1970, 1, 2, calendar=np.str_('gregorian'))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-1e1643a36ec2> in <module>
----> 1 cftime.datetime(1970, 1, 2, calendar=np.str_('gregorian'))

cftime/_cftime.pyx in cftime._cftime.datetime.__init__()

TypeError: Expected str, got numpy.str_
```

Whereas with latest `cftime`:

```python
In [1]: import cftime

In [2]: cftime.__version__
Out[2]: '1.5.0'

In [3]: import numpy as np

In [4]: cftime.datetime(1970, 1, 2, calendar=np.str_('gregorian'))
Out[4]: cftime.datetime(1970, 1, 2, 0, 0, 0, 0, calendar='gregorian', has_year_zero=False)
```

So I'm pretty confident the problem will go away once we unpin `cftime` in Iris.  It's also possible that something has changed in `matplotlib` to pass the `np.str_` down the chain and cause the error, but I don't have the skills to analyse the `matplotlib` chain!

**Comment by rcomer** [comment] 2021-06-18 09:18
By the way, we retrospectively pinned `cftime` to `>=1.5.0` in `nc-time-axis` 1.3.0.  So if you have and environment with `nc-time-axis` 1.3.0 and an earlier `cftime`, you must have created it before we realised the problem.  Sorry about that!

**Comment by valeriupredoi** [comment] 2021-06-18 09:53
@rcomer I have `cftime=1.2.1` and created the conda env yesterday, so not sure how the pin acted on it. My nc-time-axis is off PyPi, you guys pinned the deps in the pypi package too?

**Comment by rcomer** [comment] 2021-06-18 10:10
> you guys pinned the deps in the pypi package too?

Hmm, I don't know.  That's probably a question for @bjlittle or @trexfeathers

**Comment by bjlittle** [comment] 2021-06-22 09:55
We're working hard at the moment to unpin `cftime` within `iris`. 

This relies on getting `nc-time-axis` working with the latest `cftime`, and we're there now with the latest releases.

We're also working on getting `cf-units` in the same position, at which point we can unblock `iris` with regards to the latest `cftime`, at which point I suspect that we'll make an `iris` 3.0.3 release to unblock this situation.

Sound like a reasonable plan @valeriupredoi ?

**Comment by valeriupredoi** [comment] 2021-06-22 10:04
much good luck to you guys @bjlittle :crossed_fingers: Sounds very good, when do you reckon a 303 will come online? We may be releasing a bugfix release with that too, @zklaus and meself have noticed a few things that could go into a bugfix release 2.3.1 so this might fit in well too :+1:

**Comment by valeriupredoi** [comment] 2021-06-22 10:05
btw - .303 - the machine guns on the Spitfire Mk I that battled in the Battle of Britain :grin: :gb:

**Comment by bjlittle** [comment] 2021-06-22 12:37
> much good luck to you guys @bjlittle crossed_fingers Sounds very good, when do you reckon a 303 will come online? We may be releasing a bugfix release with that too, @zklaus and meself have noticed a few things that could go into a bugfix release 2.3.1 so this might fit in well too +1

@valeriupredoi We might be able to squeeze it out in the next couple of weeks. There are quite a few things competing for our time, but I'll keep you guys in the loop as to where we're at.

The best place to get the latest scoop will be https://github.com/SciTools/iris/discussions/4071 :+1:

**Comment by bjlittle** [comment] 2021-06-24 07:01
@valeriupredoi I'm going to close this issue, and we can take care of business across on `iris`, see https://github.com/SciTools/iris/discussions/4071 :+1:

**Closed by bjlittle** 2021-06-24 07:01 UTC
Labels: New: Issue
